version: '3.8'

services:
  bot:
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    command: make run
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: form
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5433:5432